package com.lap.zuzuweb.util;

import java.io.FileInputStream;
import java.io.InputStream;

import junit.framework.TestCase;

public class AuthUtilsTest extends TestCase {

	public void testIsPurchaseReceiptValid() throws Exception {
		
		ClassLoader classLoader = getClass().getClassLoader();
		InputStream is = new FileInputStream(classLoader.getResource("AppleReceiptForTest.json").getFile());

		Boolean isValid = AuthUtils.isPurchaseReceiptValid(is);
		
		System.out.println("testIsPurchaseReceiptValid result: " + isValid);
	}

	public void testIsGoogleTokenValid() throws Exception {
		String idTokenString = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImQyYjE4MGRmMWNkMmVlYzExMzhiNTNlM2E3ODBiNTNlMmNhYTlhZmQifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhdF9oYXNoIjoiYXpjZ183M01SV3hYaWhQNTBuYlRKQSIsImF1ZCI6Ijg0NjAxMjYwNTQwNi05dG5yaDgwajhrY2JjbWEyOW9taGxzZWtvdDJtbzBnbS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjY0Njc2NjI5ODczOTM1ODcyOSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI4NDYwMTI2MDU0MDYtOXRucmg4MGo4a2NiY21hMjlvbWhsc2Vrb3QybW8wZ20uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJlbWFpbCI6ImVlY2hpaEBnbWFpbC5jb20iLCJpYXQiOjE0NTcyMDQ3MzksImV4cCI6MTQ1NzIwODMzOSwibmFtZSI6IkhhcnJ5IFllaCIsInBpY3R1cmUiOiJodHRwczovL2xoNi5nb29nbGV1c2VyY29udGVudC5jb20vLTJGalpDMGJobEh3L0FBQUFBQUFBQUFJL0FBQUFBQUFBQVBjLzJra1dSYkQ0Wng4L3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJIYXJyeSIsImZhbWlseV9uYW1lIjoiWWVoIiwibG9jYWxlIjoiemgtVFcifQ.f9_5Tf26et-n1rAXOo-BmdgoZag5WFs6Cr6OpBKOEXxU_8Shq5OBRjn5yVAzeStF9cRjp1kJ9C7TILPDQHGd9y9jwIXyDeEYEKV5kiz2vrnz0IBRCgWkJsKvBT3r4zvPXY6lSdzbFoB1Uaue0m9qYqgNrTbnuQGoKodJnok51TxXLojzj0NgCmVyEuVK8CmLvk3Mq9LFu2jE5Tko8_qgimJPqXujCVrytJ36IGD3hlzYrF5z7D3f4VGYj8iA1_RGPRhqyvb5QFlesrkOIp1mqkTGAZHuUxOAMtFSXWMn9GWC5IMxNeaVOyEbcD7R-_QphUDbNPwKa1LeC3-5yBj_1A";
		Boolean isValid = AuthUtils.isGoogleTokenValid(idTokenString);
		
		System.out.println("testIsGoogleTokenValid result: " + isValid);
	}
	
	public void testIsFacebookTokenValid() throws Exception {
		String token = "CAAOxNzGZCZCPQBAEAZByeSmHZBlMJLRzZBuZBr1StKlJ8fYl8upL1ZCBhm8ouYy6T81SnZBrRZBFLZCb3Xgt0NQxDOD212Yo34WoMFs6bEUHFQKslR9clweUqEFURwhka84AhOcGwsoHPpgrQGMH2gStSHAfaBHWFVaSyznhnZBJguFalInWPanP4zvI9tLZAPoOGDqspZCO2nFHtTcPgIgsrDXBjxRSd3JLox2QZD";
		Boolean isValid = AuthUtils.isFacebookTokenValid(token);

		System.out.println("testIsFacebookTokenValid result: " + isValid);
	}
}
